# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'janoamaral/tokyo-night-tmux'

set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare
set -g @tokyo-night-tmux_show_music 0

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g default-terminal "${TERM}"

# Toggle tmux status bar
bind '\' set status
if-shell "[[ $(tmux lsw | wc -l) -le 1 ]]" 'set -g status'

set -g status on

# Enable mouse
set -g mouse on

# Start windows and panes at 1 and not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Open the new panes in the current path
bind v split-window -v -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"

# Keybindings added by plugins, etc. for my reference:
#   C-p      previous-window
#   C-n      next-window
#   R        source tmux config
#   I        install plugins
#   U        update plugins
#   M-u      remove/uninstall plugins not on the list
set -g @sessionx-bind 's'

set -g status-right ""
set -g status-style bg="default"

# Initialize TMUX plugin manager (must be kept at the very bottom of this file)
run '~/.tmux/plugins/tpm/tpm'
